// CHOSES A PREVOIR POUR CETTE PAGE: //


// 1- ECOUTER LE BTN DE VALIDATION DE COMMANDE SUR LA PAGE PANIER {
//      RECUPERER L ECOUTE
//      ENVOYER LES DATAS AU BACK END? API? VIA POST?
//      ATTENDRE LA REPONSE 
//      RETOURNER LA REPONSE DANS SON CONTENEUR ( n° de commande) }
