// CHOSES A PREVOIR POUR CETTE PAGE: //


// 1- ECOUTER LE BTN D AJOUT AU PANIER SUR LA PAGE PRODUCT {
//      RECUPERER L ECOUTE
//      RETOURNER L ECOUTE DONC LE PRODUIT CHOISI ET L AFFICHER DANS SON CONTENEUR (img miniature / title / lense / price / qte)
//      AJOUTER LE PRODUIT AU LOCAL STORAGE ?? }


// 2- ECOUTER UN BTN DELETE PERMETTANT DE SUPPRIMER LE/LES PRODUITS DU PANIER {
//      RECUPERER L ECOUTE
//      RETOURNER L ECOUTE ET SUPPRIMER LE/LES PRODUITS SELECTIONNES VISUELLEMENT ET DANS LE PANIER
//      SUPPRIMER LE PRODUIT DU LOCAL STORAGE PEUT IMPORTE LA QTE
//      UPDATE LE PANIER }


// 3- ECOUTER UN BTN + PERMETTANT D AJOUTER LE MEME PRODUIT {
//      RECUPERER L ECOUTE
//      RETOURNER L ECOUTE ET AJOUTER +1 A LA QUANTITE
//      AJOUTER +1 AU LOCAL STORAGE
//      ADDITIONNER LE PRICE DU PRODUIT AU PRICE TOTAL => UPDATE LE PANIER? }


// 4- ECOUTER UN BTN - PERMETTANT D ENLEVER LE MEME PRODUIT {
//      RECUPERER L ECOUTE
//      RETOURNER L ECOUTE ET SOUSTRAIRE -1 A LA QUANTITE
//      SOUSTRAIRE -1 AU LOCAL STORAGE
//      SOUSTRAIRE LE PRICE DU PRODUIT AU PRICE TOTAL => UPDATE LE PANIER? }


// 5- ECOUTER LES DIFFERENTS INPUT DU FORMULAIRE {
//      SI REPONSE => OK => VALIDER => BASCULE SUR LA FENETRE DE CONFIRMATION DE COMMANDE
//      SI REPONSE => FALSE => DISPLAY ERREUR ET REDEMANDER L ACTION }


//  Pour les routes POST, l’objet contact envoyé au serveur doit contenir les champs
//firstName, lastName, address, city et email. Le tableau des produits envoyé au
//backend doit être un array de strings product_id. Les types de ces champs et leur
//présence doivent être validés avant l’envoi des données au serveur.
